
  - name: Installing Softwares in Ubuntu Server
    hosts: ec2
    become: yes
    tasks:
      - name: Update the apt cache
        apt:
          update_cache: yes
          
      - name: Install OpenJDK 11
        apt:
          name: openjdk-11-jdk
          state: present

      - name: Verify Java installation
        shell: java -version
        register: java_version_output

      - name: Display Java version
        debug:
          msg: "{{ java_version_output.stderr_lines }}"

    

